name: run fabric8 istio integration test
description: run fabric8 istio integration test
runs:
  using: "composite"
  steps:
    - name: run fabric8 istio integration test
      shell: bash
      run: |
        docker load -i /tmp/docker/images/spring-cloud-kubernetes-fabric8-istio-it.tar
        cd spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-istio-it/
        ../.././mvnw clean install -Dskip.build.image=true
        cd ../..

        echo "TESTCONTAINERS_REUSE_ENABLE=true" >> $GITHUB_ENV
