spring:
  application:
    name: spring-cloud-kubernetes-configuration-watcher-it
  cloud:
    bus:
      refresh:
        enabled: false #disable this because we are going to provide our own refresh listener for testing purposes
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
management:
  endpoint:
    health:
      probes:
        enabled: true
---
spring:
  cloud:
    bus:
      enabled: true
    stream:
      default-binder: rabbit
  config:
    activate:
      on-profile:
---
spring:
  cloud:
    bus:
      enabled: true
    stream:
      default-binder: kafka
  config:
    activate:
      on-profile:
