# common steps before running actula tests for both
# when a cache of test times is presen and when it is not present

name: pre-test-actions
description: pre-test-actions
inputs:
  jdk-version:
    description: 'Java version to use in artifact name'
    required: false
    default: '17'
runs:
  using: "composite"

  steps:

    - name: set env variables
      uses: ./.github/workflows/composites/env-variables

    - name: setup project jdk-17
      uses: ./.github/workflows/composites/setup-jdk17
      if: env.BASE_BRANCH == 'main'

    - name: cache local maven repository
      uses: ./.github/workflows/composites/cache
      with:
        jdk-version: ${{ inputs.jdk-version }}

    - name: restore common images
      uses: ./.github/workflows/composites/restore-docker-images

    - name: build project
      shell: bash
      run: |
        ./mvnw clean install -P 'run-on-github-actions' -Dspring-boot.build-image.skip=true -DskipITs -DskipTests -T1C -U -B -q  

    - name: build controllers project
      uses: ./.github/workflows/composites/build-controllers-project

    - name: build integration tests project
      uses: ./.github/workflows/composites/build-integration-tests-project

    - name: download tests
      uses: actions/download-artifact@v4
      with:
        name: tests-jdk${{ inputs.jdk-version }}.txt
        path: /tmp




