spring:
  application:
    name: poll-reload
  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: shutdown
        mode: polling
        period: 5000
      config:
        paths:
          - /tmp/application.properties

