apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  labels:
    app: service-busybox
spec:
  selector:
    app: busybox
  type: ClusterIP
  ports:
    - name: busybox-port
      port: 8080
      targetPort: 80
